config/routes.rb
GestorApp::Application.routes.draw do
  
  resources :charges

  resources :user_org_charges, :collection => { :create => :post } 
    

  resources :organic_units

  resources :competences do
    member do
      get 'delete_charge'
    end
  end

  resources :user_competences, :collection => { :create => :post }

  resources :charge_competences
  resources :sessions, :only => [:new, :create, :destroy]

  get "sessions/new"

  resources :users do
    member do
      get 'edit_password'
      put 'update_password'
    end
  end

  
  get "pages/home"

  get "pages/pessoas"

  get "pages/organic_units"

  get "pages/competences"

  root :to => "pages#home"

  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/organic_unit.rb
# == Schema Information
#
# Table name: organic_units
#
#  id          :integer         not null, primary key
#  name        :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  description :string(255)
#  id_padre    :integer
#

class OrganicUnit < ActiveRecord::Base
	attr_accessible :name, :description, :id_padre

	validates :name,	:presence => true,
						:uniqueness => { :case_sensitive => false }

	has_many 		:org_sons, 	:class_name => "OrganicUnit"
	belongs_to 	:org_father, :class_name => "OrganicUnit",
							:foreign_key => "org_father_id"

	has_many :user_org_charges, :dependent => :destroy
  has_many :charges,          :through => :user_org_charges
  has_many :users,    				:through => :user_org_charges 	
  
  def self.search(search)
    if search
      #all(:conditions => ['name LIKE ?', "%#{search}%"])
      where('name LIKE ?', "%#{search}%")
    else
      #all
      scoped
    end
  end
  						
end

app/controllers/organic_units_controller.rb
class OrganicUnitsController < ApplicationController

  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]

  # GET /organic_units
  # GET /organic_units.json
  def index
    @organic_units = OrganicUnit.search(params[:search]).paginate(:per_page => 2, :page => params[:page])
    @title = "Organic Units"
    @orgs = OrganicUnit.all
  end

  # GET /organic_units/new
  # GET /organic_units/new.json
  def new
    @title = "New Organic Unit"
    @organic_unit = OrganicUnit.new
    @units = OrganicUnit.all

  end

  # POST /organic_units
  # POST /organic_units.json
  def create
    @organic_unit = OrganicUnit.new(params[:organic_unit])
    if @organic_unit.save
      flash[:success] = "Organic unit created"
      redirect_to @organic_unit#, notice: 'Organic unit was successfully created.' 
    else
      render action: "new"
    end
  end
    
  # GET /organic_units/1
  # GET /organic_units/1.json
  def show
    @organic_unit = OrganicUnit.find(params[:id])
    @title = @organic_unit.name
    @users = @organic_unit.users
  end

  # GET /organic_units/1/edit
  def edit
    @organic_unit = OrganicUnit.find(params[:id])
    @title = "Edit organic unit"
    @units = OrganicUnit.all

  end

  # PUT /organic_units/1
  # PUT /organic_units/1.json
  def update
    @organic_unit = OrganicUnit.find(params[:id])
    if @organic_unit.update_attributes(params[:organic_unit])
      redirect_to @organic_unit, notice: 'Organic unit was successfully updated.'
    else
      @title = "Edit organic unit"
      render action: "edit" 
    end
  end

  # DELETE /organic_units/1
  # DELETE /organic_units/1.json
  def destroy
    OrganicUnit.find(params[:id]).destroy
    flash[:success] = "Org unit deleted."
    redirect_to organic_units_url
  end


  private
    def authenticate
      deny_access unless signed_in?
    end   
end

app/helpers/organic_units_helper.rb
module OrganicUnitsHelper
end

app/views/organic_units/_form.html.erb
<%= form_for(@organic_unit) do |f| %>
  <% if @organic_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organic_unit.errors.count, "error") %> prohibited this organic_unit from being saved:</h2>

      <ul>
      <% @organic_unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label "Organizacion padre" %>
    <%= f.collection_select :id_padre, @units, :id, :name, :prompt => 'Select organic unit' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organic_units/_organizaciones.html.erb
<%= will_paginate %>
<table>
  <tr>
    <th width='40%'>Name</th>
    <th width='40%'>Description</th>
    <th width='20%'>Parent Org.</th>
    <th></th>
    <th></th>
  </tr>

<% @organic_units.each do |organic_unit| %>
  <tr>
    <td><%= link_to organic_unit.name, organic_unit %></td>
    <td><%= organic_unit.description %></td>
      <% if !organic_unit.id_padre.nil? %>
        <% @org_padre = OrganicUnit.find(OrganicUnit.find(organic_unit.id_padre)) %>
        <td><%= link_to @org_padre.name, @org_padre %></td>
      <% else %>
        <td>--</td>
      <% end %>
    <td><%= link_to 'Edit', edit_organic_unit_path(organic_unit) %></td>
    <td><%= link_to 'Delete', organic_unit, confirm: 'Are you sure?', method: :delete, :title => "Delete #{organic_unit.name}" %></td>
  </tr>
<% end %>
</table>
<%= will_paginate %>

app/views/organic_units/edit.html.erb
<h1>Editing organic_unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @organic_unit %> |
<%= link_to 'Back', organic_units_path %>

app/views/organic_units/index.html.erb
<h1><span><%= @title %></span></h1>
<%= link_to 'New Organic unit', new_organic_unit_path %>
<%= form_tag competences_path, :method => 'get', :id => "organizaciones_search" do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>


<div class='contents'>
	<% if !@orgs.empty? %>
		<% @orgs.each do |org| %>
			<ul>
				<% if org.id_padre.nil? %>
					<li> <%= link_to org.name, org %></li>
					<% @orgs_hijas = OrganicUnit.find_all_by_id_padre(org.id) %>
					<% if !@orgs_hijas.empty? %>
						<ul>
							<% @orgs_hijas.each do |hija| %>
								<li><%= link_to hija.name, hija %></li>
							<% end%>
						</ul>
					<% end %>
				<% end %>
			</ul>
		<% end %>
	<% end %>
<!-- la tabla de los usuarios se ha puesto en partial _usuarios.html.erb -->
<!-- para hacer uso de Ajax -->
<div id="organizaciones"><%= render 'organizaciones' %></div>

<div class='clear_all'></div>
</div>
</div>
<br />

app/views/organic_units/index.js.erb
$("#organizaciones").html("<%= escape_javascript(render("organizaciones")) %>")

app/views/organic_units/new.html.erb
<h1><%= @title %></h1>

<%= render 'form' %>

<%= link_to 'Back', organic_units_path %>

app/views/organic_units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @organic_unit.name %><br />
  <b>Description:</b>
  <%= @organic_unit.description %><br />
  <b>Organización padre:</b>
  <% if !@organic_unit.id_padre.nil? %>
	  <%= link_to OrganicUnit.find(OrganicUnit.find(@organic_unit.id_padre)).name,
	  						OrganicUnit.find(OrganicUnit.find(@organic_unit.id_padre))%>
	<% else %>
		<p>Raiz</p>
	<% end %><br />

	<b>Suborganizaciones:</b>
  	<% @orgs = OrganicUnit.find_all_by_id_padre(@organic_unit.id) %>
  	<% if !@orgs.nil? %>
	  	<ul>
	  		<% @orgs.each do |org| %>
	  		<li><%= link_to org.name, org %></li>
	  		<% end %>
	  	</ul>
	  	<% else %>
	  		<p>Sin suborganizaciones.</p>
	  	<% end %>
</p><br />
<p>
	
  <%= link_to 'Add members', new_user_org_charge_path(params = :organic_unit_id => @organic_unit.id) %>
</p><br />

<% if !@users.empty? %>
		<p>
			<b> Miembros participantes </b>
		</p>
		<table>
			<tr>
				<th width='40%'>Name</th>
				<th width='40%'>Charge</th>
				<th></th>
				<th></th>
			</tr>
			
				<% @organic_unit.user_org_charges.each do |u| %>
					
					<tr>
						<td> <%= link_to u.user.name, u.user %> </td>
						<% if !u.charge.nil? %>
							<td> <%= link_to u.charge.name, u.charge %> </td>
						<% else %>
							<td>Sin cargo</td>
						<% end %>
						<td> <%= link_to 'Delete', u, :confirm => 'Are you 	sure?', :method => :delete %></td>
						<td> <%= link_to 'Change charge', edit_user_org_charge_path(u) %> </td>
					</tr>
				<% end %>
			
		</table>
		<% else %>
			<p><b>No hay ningún miembro en esta organización.</b></p>
	<% end %>


<%= link_to 'Edit', edit_organic_unit_path(@organic_unit) %> |
<%= link_to 'Back', organic_units_path %>