config/routes.rb
GestorApp::Application.routes.draw do
  
  resources :charges

  resources :user_org_charges, :collection => { :create => :post } 
    

  resources :organic_units

  resources :competences do
    member do
      get 'delete_charge'
    end
  end

  resources :user_competences, :collection => { :create => :post }

  resources :charge_competences
  resources :sessions, :only => [:new, :create, :destroy]

  get "sessions/new"

  resources :users do
    member do
      get 'edit_password'
      put 'update_password'
    end
  end

  
  get "pages/home"

  get "pages/pessoas"

  get "pages/organic_units"

  get "pages/competences"

  root :to => "pages#home"

  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer         not null, primary key
#  name               :string(255)
#  surname            :string(255)
#  nif                :string(255)
#  email              :string(255)
#  phone              :integer
#  address            :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  encrypted_password :string(255)
#  salt               :string(255)
#  admin              :boolean         default(FALSE)
#

require 'digest'
class User < ActiveRecord::Base

	attr_accessor :password, :password_confirmation, :set_the_password, :old_password

	attr_accessible :name, :surname, :nif, :email, :phone, :address,
					:password, :password_confirmation, :old_password

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name,	:presence => true,
						:length => { :maximum => 50 }

	validates :surname,	:presence => true,
						:length => { :maximum => 50 }
	
	validates :email, 	:presence => true,
						:format => { :with => email_regex },
						:uniqueness => { :case_sensitive => false }
	
	validates  :password,	:presence => true, 
							:confirmation => true,
							:length => { :within => 6..40 },
              :on => :create

	before_save :encrypt_password

  #############################################################
  ################# Relationships #############################
  has_many :user_competences, :dependent => :destroy
  has_many :competences, :through => :user_competences
  ## el dependent es para que cuando se elimine un usuario
  ## automaticamente se eliminen las entradas de la tabla de 
  ## la relacion en las que participe.           
  has_many :user_org_charges, :dependent => :destroy
  has_many :charges,          :through => :user_org_charges
  has_many :organic_units,    :through => :user_org_charges                   
  #############################################################
  #############################################################


  #para la busqueda de usuarios
  def self.search(search)
    if search
      #all(:conditions => ['name LIKE ?', "%#{search}%"])
      where('name LIKE ?', "%#{search}%")
    else
      #all
      scoped
    end
  end

  def has_password?(submitted_password)
    	encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
   	user = find_by_email(email)
   	return nil  if user.nil?
   	return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
  	user = find_by_id(id)
  	(user && user.salt == cookie_salt) ? user : nil
  end

    ######################################################
    ############### Para competences #####################
    ######################################################
    
    #######Devuelve las competence de user dado el id#####
    #def competences#(user)
      #user = find_by_id(id)
     # competences
    #end
    ######################################################
    ######################################################
    #######Comprueba si tiene competencias ###############
    
    #busca si el user tiene una competencia en concreto
    def competence?(competence)
      user_competence.find_by_competence_id(competence)
    end

    def competences?#(user)
      #user = find_by_id(id)
      competences.all.empty?
    end
    ######################################################
    ######################################################
    ####Crea una entrada en la tabla relacion competencia#
    def crea_competencia(id_competencia, nivel)
      #user = find_by_id(id)
      competences.create(:competencia_id => id_competencia,
                              :level => nivel)
    end
    ######################################################
    ####Elimina competencia del usuario###################
    def elimina_competencia(id_competencia)
      #user = find_by_id(id)
      competences.find_by_id(id_competencia).destroy
    end
    ######################################################
    ####Modifica el nivel en una competencia##############
    def modifica_nivel_competencia(id_competencia, nivel)
      competences.find_by_id(id_competencia).update_attribute(:level, nivel)
    end
    ######################################################


    ######################################################

  private
    
    def encrypt_password

      if self.set_the_password
        self.salt = make_salt unless has_password?(password)
        self.encrypted_password = encrypt(password)
      end
    end
    

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:index, :edit, :update, :destroy]
  before_filter :correct_user, :only => [:edit, :update, :edit_password, :update_password]
  before_filter :admin_user, :only => :destroy

  #before_filter :modifica_pass, :only => :update_password
  # GET /users
  # GET /users.json
  def index
    @users = User.search(params[:search]).paginate(:per_page => 2, :page => params[:page])
    @title = "Users"
    #if params[:search]
     # @users = User.all(:conditions => ['name LIKE ?', 
      #                                        "%#{params[:search]}%"])
    #else
     # @users = User.all
      #@title = "All users"
    #end  
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @title = @user.name
    #este tiene solo el nombre de las competencias
    #@competences = @user.competences

    #este tiene el user_id competence_id level
    @competences = @user.user_competences
    
    
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @title = "Sign up"
    #@action = "New Action"
  end

  # GET /users/1/edit
  def edit
    #@user = User.find(params[:id])
    #lo ponemos en la zona privada dentro de correct_user
    @title = "Edit user"
    #@action = "Edit Action"
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.set_the_password = true
    #@update_pass = 0
    if @user.save
      sign_in @user
      flash[:success] = "Bienvenido al gestor de usuarios"
      redirect_to @user
    else
      @title = "Sign up"
      render 'new'
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    #@user = User.find(params[:id])
    
    #@update_pass = 0
    #puts @change_password
    if @user.update_attributes(params[:user])
                               # :name    => params[:user][:name],
      #                        :surname  => params[:user][:surname],
       #                       :nif      => params[:user][:nif],
        #                      :address  => params[:user][:address],
         #                     :email    => params[:user][:email],
          #                    :phone    => params[:user][:phone])
    #if @user.valid?
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render 'edit'
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_path
  end

  def edit_password
    @title = "Editar password"
  end

  def update_password
    #ha llamado antes a correct_user
    @title = "Update password"

    @user.set_the_password = true

    if @user.update_attributes(params[:user])
      flash[:success] = "Password modificada"
      redirect_to @user
    else
      @title = "Editar password"
      render 'edit_password'
    end   
    ##############################
  end

  private

    def authenticate
      deny_access unless signed_in?
      #deny_access definido en sessions_helper.rb
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
      #current_user? definido en sessions_helper.rb
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
   
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br />
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :nif %><br />
    <%= f.text_field :nif %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <!-- ########## Hacer que esto solo sea si viene de new ####-->
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <!-- ###################################################### -->
  <div class="actions">
    <%= f.submit "Update"%>
  </div>
<% end %>

app/views/users/_form_edit.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br />
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :nif %><br />
    <%= f.text_field :nif %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit "Update"%>
  </div>
<% end %>

app/views/users/_usuarios.html.erb
<%= will_paginate %>
<table cellpadding='0' cellspacing='0'>
  <tr>
    <th width='20%'>Name</th>
    <th width='40%'>Surname</th>
    <!--
    <th>Nif</th>-->
    <th width='30%'>Email</th>
    <!--<th>Phone</th>
    <th>Address</th>-->
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.name, user %></td>
    <td><%= user.surname %></td>
    <!--<td><%= user.nif %></td>-->
    <td><%= user.email %></td>
    <!--<td><%= user.phone %></td>
    <td><%= user.address %></td>
    <td><%= link_to 'Show', user %></td>-->
    <% if current_user.admin? || current_user?(user) %>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Delete', user, :confirm => 'Are you sure?', :method => :delete,
                                      :title => "Delete #{user.name}" %></td>
    <% end %>
  </tr>
<% end %>
</table>

<%= will_paginate %>

app/views/users/edit.html.erb
<h1><%= @title %></h1>

<%= render 'form_edit' %>

<%= link_to 'Back', @user %> |
<!-- <%= link_to 'Back', users_path %> -->

app/views/users/edit_password.html.erb
<h1><%= @title %></h1>

<%= form_for(@user, :url => { :action => "update_password" }, :method => :put) do |f| %>
   		<div class="field">
    		<%= f.label "Password" %>
      		<%= f.password_field :old_password %>
    	</div>
    	<div class="field">
      		<%= f.label "New Password" %>
      		<%= f.password_field :password %>
      </div>
      <div class="field">
      		<%= f.label "New Password Confirmation" %>
      		<%= f.password_field :password_confirmation %>
		  </div>
      		
    	<div class="actions">
    		<%= f.submit "Change password"%>
  		</div>
<% end %>

<%= link_to 'Back', @user %>  

app/views/users/index.html.erb
<h1><span><%= @title %></span></h1>
 <%= link_to 'New User', new_user_path %>

 <!-- :id => "usuarios_search es para hacer el buscador con Ajax"-->
  <%= form_tag users_path, :method => 'get', :id => "usuarios_search" do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>



<div class='contents'>

<!-- la tabla de los usuarios se ha puesto en partial _usuarios.html.erb -->
<!-- para hacer uso de Ajax -->
<div id="usuarios"><%= render 'usuarios' %></div>

<div class='clear_all'></div>
</div>
</div>
<br />

app/views/users/index.js.erb
$("#usuarios").html("<%= escape_javascript(render("usuarios")) %>")

app/views/users/new.html.erb
<h1><%= @title %></h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1> <span><%= "#{@user.name} #{@user.surname}" %></span> </h1>
<p>
  <b>Name</b><br />
  <%= @user.name %>
</p>

<p>
  <b>Surname</b><br />
  <%= @user.surname %>
</p>

<p>
  <b>Nif</b><br />
  <%= @user.nif %>
</p>

<p>
  <b>Email</b><br />
  <%= link_to @user.email %>
</p>

<p>
  <b>Phone</b><br />
  <%= @user.phone %>
</p>

<p>
  <b>Address</b><br />
  <%= @user.address %>
</p>
<br />

<p>
  <%= link_to 'Competencia nueva', new_user_competence_path(params = :user_id => @user.id) %>
</p><br />
<% unless @competences.empty? %>
  <b>Competencias</b><br />
    <table>
      <tr>
        <th width='30%'>Name</th>
        <th width='30%'>Level</th>
        <th></th>
        <th></th>
      </tr>
      <!--@competences array de competencias del user-->
      <% @competences.each do |cuser| %>
        <tr>
          <td> <%= link_to cuser.competence.name, cuser.competence %> </td>
          <td> <%= cuser.level %> </td>
          <td> <%= link_to 'Edit level', edit_user_competence_path(cuser) %> </td>
          <td> <%= link_to 'Delete', cuser, :confirm => 'Are you sure?',
                                            :method => :delete,
                                            :title => "Delete#{cuser.competence.name}"%></td>
        </tr>
      <% end %>
      </table>
      <% end %>
 


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Edit password', edit_password_user_path(@user) %> |
<%= link_to 'Back', users_path %>