config/routes.rb
GestorApp::Application.routes.draw do
  
  resources :charges

  resources :user_org_charges, :collection => { :create => :post } 
    

  resources :organic_units

  resources :competences do
    member do
      get 'delete_charge'
    end
  end

  resources :user_competences, :collection => { :create => :post }

  resources :charge_competences
  resources :sessions, :only => [:new, :create, :destroy]

  get "sessions/new"

  resources :users do
    member do
      get 'edit_password'
      put 'update_password'
    end
  end

  
  get "pages/home"

  get "pages/pessoas"

  get "pages/organic_units"

  get "pages/competences"

  root :to => "pages#home"

  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/charge.rb
# == Schema Information
#
# Table name: charges
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Charge < ActiveRecord::Base

	attr_accessible :name

	validates :name,	:presence => true,
						:uniqueness => { :case_sensitive => false }

	#############################################################
  ###################### Relationships ########################
  has_many :charge_competences, :dependent => :destroy
  has_many :competences, :through => :charge_competences
	## el dependent es para que cuando se elimine una competencia
	## automaticamente se eliminen las entradas de la tabla de 
	## la relacion en las que participe.                              
  #############################################################
  #############################################################

  def self.search(search)
    if search
      #all(:conditions => ['name LIKE ?', "%#{search}%"])
      where('name LIKE ?', "%#{search}%")
    else
      #all
      scoped
    end
  end
  
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  # GET /charges
  # GET /charges.json
  def index
    @title = "Listado de cargos"
    @charges = Charge.search(params[:search]).paginate(:per_page => 2, :page => params[:page])
  end

  # GET /charges/1
  # GET /charges/1.json
  def show
    @charge = Charge.find(params[:id])
    @competences = @charge.competences
    @title = "Cargo"
    
  end

  # GET /charges/new
  # GET /charges/new.json
  def new
    @charge = Charge.new
  end

  # GET /charges/1/edit
  def edit
    @charge = Charge.find(params[:id])
  end

  # POST /charges
  # POST /charges.json
  def create
    @charge = Charge.new(params[:charge])
    if @charge.save
      redirect_to @charge, notice: 'Charge was successfully created.' 
    else
      render action: "new"
    end
  end

  # PUT /charges/1
  # PUT /charges/1.json
  def update
    @charge = Charge.find(params[:id])
    if @charge.update_attributes(params[:charge])
      redirect_to @charge, notice: 'Charge was successfully updated.'
    else
      render action: "edit"
    end
  end

  # DELETE /charges/1
  # DELETE /charges/1.json
  def destroy
    @charge = Charge.find(params[:id])
    @charge.destroy
    redirect_to charges_url
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_cargos.html.erb
<%= will_paginate %>
<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>

<% @charges.each do |charge| %>
  <tr>
    <td><%= link_to charge.name, charge %></td>
    <td><%= link_to 'Edit', edit_charge_path(charge) %></td>
    <td><%= link_to 'Delete', charge, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<%= will_paginate %>

app/views/charges/_form.html.erb
<%= form_for(@charge) do |f| %>
  <% if @charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

      <ul>
      <% @charge.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charges/edit.html.erb
<h1>Editing charge</h1>

<%= render 'form' %>

<%= link_to 'Show', @charge %> |
<%= link_to 'Back', charges_path %>

app/views/charges/index.html.erb
<h1><span><%= @title %></span></h1>

<%= link_to 'New Charge', new_charge_path %>

<%= form_tag competences_path, :method => 'get', :id => "cargos_search" do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
  <% end %>

<div class='contents'>
<!-- la tabla de los usuarios se ha puesto en partial _usuarios.html.erb -->
<!-- para hacer uso de Ajax -->
<div id="cargos"><%= render 'cargos' %></div>

<div class='clear_all'></div>
</div>
</div>
<br />

app/views/charges/index.js.erb
$("#cargos").html("<%= escape_javascript(render("cargos")) %>")

app/views/charges/new.html.erb
<h1>New charge</h1>

<%= render 'form' %>

<%= link_to 'Back', charges_path %>

app/views/charges/show.html.erb
<h1><span><%= @title %></span></h1>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @charge.name %>
</p>
	<% if !@competences.empty? %>
		<p>
			<b> Competencias asociadas al cargo </b>
		</p>
		<table>
			<tr>
				<th> Name </th>
				<th></th>
			</tr>
				<% @charge.charge_competences.each do |c| %>
					
					<tr>
						<td> <%= link_to c.competence.name, c.competence %> </td>
						<td> <%= link_to 'Delete', c, :confirm => 'Are you 	sure?', :method => :delete %></td>
					</tr>
				<% end %>
			
		</table>
		<% else %>
			<p><b>No hay competencias asociadas al cargo</b></p>
	<% end %>
<p>
  <%= link_to 'Competencia nueva', new_charge_competence_path(params = :charge_id => @charge.id) %>
</p><br />

<%= link_to 'Edit', edit_charge_path(@charge) %> |
<%= link_to 'Back', charges_path %>