config/routes.rb
GestorApp::Application.routes.draw do
  
  resources :charges

  resources :user_org_charges, :collection => { :create => :post } 
    

  resources :organic_units

  resources :competences do
    member do
      get 'delete_charge'
    end
  end

  resources :user_competences, :collection => { :create => :post }

  resources :charge_competences
  resources :sessions, :only => [:new, :create, :destroy]

  get "sessions/new"

  resources :users do
    member do
      get 'edit_password'
      put 'update_password'
    end
  end

  
  get "pages/home"

  get "pages/pessoas"

  get "pages/organic_units"

  get "pages/competences"

  root :to => "pages#home"

  
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
</header>

<nav>
<div class='menus'>
  <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if signed_in? %>
        <li><%= link_to "Pessoas", users_path %></li>
        <li><%= link_to "Profile", current_user %></li>
        
        <li><%= link_to "Org. Units", organic_units_path %></li>
        <li><%= link_to "Charges", charges_path %></li>
        <li><%= link_to "Competences", competences_path %></li>
        <li></li>
        <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
    </div>
  </nav>
  </div>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class='site'>
      <div class='top_menus'>
  	      <%= render 'layouts/header' %>   
          <div class="round" id='container'>
  		     	
              <% flash.each do |key, value| %>
              <div class="flash <%= key %>"><%= value %></div>
              <% end %>
              <div class='page_title'>
                
                <%= yield %>
              
      	     
      	     <%= render 'layouts/footer' %>
             <%= debug(params) if Rails.env.development? %> 
          </div>
      </div>
      </div>
  </body>
</html>